version: "2"

volumes:
  project:

services:
  theia-server:
    build: .
    container_name: theia-server
    volumes:
      - project:/home/project
    ports:
      - 3000:3000
    restart: unless-stopped
