version: "2"

volumes:
  project:
  caddydata:
  caddyconfig:

networks:
  local:

services:
  gatekeeper:
    image: registry.digitalocean.com/watheia/theia-server:gatekeeper
    container_name: gatekeeper
    restart: unless-stopped
    environment:
      GK_ACME_CA: "${GK_ACME_CA}"
      GK_ACME_EMAIL: "${GK_ACME_EMAIL}"
      GK_SITE: "${GK_SITE}"
      GK_GOOG_CLIENT_ID: "${GK_GOOG_CLIENT_ID}"
      GK_GOOG_CLIENT_SECRET: "${GK_GOOG_CLIENT_SECRET}"
    volumes:
      - caddyconfig:/var/caddy/config
      - caddydata:/var/caddy/data
    networks:
      - local
    ports:
      - 8080:80
      - 8443:443

  theia-server:
    build: .
    container_name: theia-server
    restart: unless-stopped
    volumes:
      - project:/home/project
    networks:
      - local
    ports:
      - 3000:3000
